@startuml
'https://plantuml.com/class-diagram

object Turnering
object Main
object Hold
object KnockoutTurnering
object PointTurnering
object Kamp

Main *-- Turnering
Turnering <|-- KnockoutTurnering
Turnering<|-- PointTurnering
KnockoutTurnering o-- "16.." Hold
PointTurnering o-- "16.." Hold
Turnering o-- Kamp
Kamp o-- "2" Hold
@enduml