@startuml
'https://plantuml.com/class-diagram

abstract class Turnering
class Main
class Hold
class KnockoutTurnering
class PointTurnering
class Kamp
Main o-- Ui
Ui *-- Turnering
Turnering <|-- KnockoutTurnering
Turnering<|-- PointTurnering
Turnering o-- "16" Hold
Turnering o-- Kamp
Kamp o-- "2" Hold

class Ui{
 - Scanner brugerInput
 + opretTurnering()
 + seTurnering()
 + seHold()
}

class Main {
 + main(String[] args)
 - Ui ui
}
class Kamp{
- int kampLængde
- int kampID
- Hold[2] holdKamp
- int[2] resultat
+ findVinderKnockOut()
+ findVinderPoint()
}

class Hold{
- int points
- String holdNavn
- int antalSpillere
- int holdID
- int målScore
+ getPoints()
+ setPoints()
+ toString()

}
abstract class Turnering{
- Random random
- Scanner filLæser
- int nuværendeKamp
- Arraylist <Kamp> kampOpsættelse
- Arraylist<Hold>holdListe
+ {abstract}læsHoldData()
+ {abstract}fjernOverskud()
+ {abstract}opsætKamp()
+ {abstract}kampCyklus()
}
class KnockoutTurnering{

}
class PointTurnering{
+ tælPoint()
+ opdaterMålScore()
+ opdaterKampScore()
}


@enduml